version: '3.8'

services:
  app:
    build: .
    stdin_open: true
    tty: true
    working_dir: /diesel-demo
    environment:
      - USER=tabakazu
      - DATABASE_URL=mysql://root:@mysql:3306/diesel_demo
    ports:
      - '3000:3000'
    volumes:
      - .:/diesel-demo:cached
      - target:/diesel-demo/target
      - cargo_package:/usr/local/cargo
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=diesel_demo
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  target:
  mysql_data:
  cargo_package:
