FROM rust:1.43.1

# Usage
# $ docker build ./ -t rust-demo
# $ docker run --rm -v $PWD:/workspace -e USER=tabakazu -it rust-demo /bin/bash
# docker > cd /workspace
# docker > rustc main.rs
# docker > ./main
# 
# Use Cargo
# docker > cd /workspace
# docker > cargo new hello_cargo --bin
# docker > cd hello_cargo
# docker > cargo run
