version: '3.8'

services:
  app:
    image: rust:1.43.1
    stdin_open: true
    tty: true
    # command: cargo run
    working_dir: /guessing_game
    environment:
      - USER=tabakazu
    ports:
      - '3000:3000'
    volumes:
      - .:/guessing_game:cached
      - target:/guessing_game/target

volumes:
  target:
