version: '3.8'

services:
  app:
    image: rust:1.43.1
    stdin_open: true
    tty: true
    working_dir: /practice
    environment:
      - USER=tabakazu
    ports:
      - '3000:3000'
    volumes:
      - .:/practice:cached
      - target:/practice/target
      - cargo_package:/usr/local/cargo

volumes:
  target:
  cargo_package:
