// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tabakazu/aws-sdk-ec2-demo/domain (interfaces: IEC2Resource)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	domain "github.com/tabakazu/aws-sdk-ec2-demo/domain"
	reflect "reflect"
)

// MockIEC2Resource is a mock of IEC2Resource interface
type MockIEC2Resource struct {
	ctrl     *gomock.Controller
	recorder *MockIEC2ResourceMockRecorder
}

// MockIEC2ResourceMockRecorder is the mock recorder for MockIEC2Resource
type MockIEC2ResourceMockRecorder struct {
	mock *MockIEC2Resource
}

// NewMockIEC2Resource creates a new mock instance
func NewMockIEC2Resource(ctrl *gomock.Controller) *MockIEC2Resource {
	mock := &MockIEC2Resource{ctrl: ctrl}
	mock.recorder = &MockIEC2ResourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIEC2Resource) EXPECT() *MockIEC2ResourceMockRecorder {
	return m.recorder
}

// FindById mocks base method
func (m *MockIEC2Resource) FindById(arg0 string) (*domain.EC2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", arg0)
	ret0, _ := ret[0].(*domain.EC2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById
func (mr *MockIEC2ResourceMockRecorder) FindById(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockIEC2Resource)(nil).FindById), arg0)
}
