version: '3.4'

services:
  goapp:
    build:
      context: .
      dockerfile: ./.dockerdev/goapp/Dockerfile
    stdin_open: true
    tty: true
    environment:
      - EDITOR=vi
    ports:
      - '8090:8080'
    volumes:
      - .:/go/src/github.com/tabakazu/gortfolio:cached
      - go_pkg_mod:/go/pkg/mod
    depends_on:
      - mysql
  mysql:
    build:
      context: .
      dockerfile: ./.dockerdev/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gortfolio_dev
    volumes:
      - mysql_data:/var/lib/mysql
  migrate:
    image: migrate/migrate
    # command: ["-database", "mysql://root:root@tcp(mysql:3306)/gortfolio_dev", "-path", "./migrations", "up"]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - mysql

volumes:
  go_pkg_mod:
  mysql_data:
