version: '3.8'

services:
  app:
    image: rust:1.43.1
    stdin_open: true
    tty: true
    # command: cargo run
    working_dir: /dining_philosophers
    environment:
      - USER=tabakazu
    ports:
      - '3000:3000'
    volumes:
      - .:/dining_philosophers:cached
      - target:/dining_philosophers/target

volumes:
  target:
