[package]
name = "oop-demo"
version = "0.1.0"
authors = ["tabakazu <tkazz.bd1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
