# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'activerecord'
gem 'activemodel'
gem 'rake'
gem 'mysql2', '>= 0.4.4', '< 0.6.0'