// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tabakazu/awscaller/domain/resource (interfaces: CallerResource)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/tabakazu/awscaller/domain/model"
	reflect "reflect"
)

// MockCallerResource is a mock of CallerResource interface
type MockCallerResource struct {
	ctrl     *gomock.Controller
	recorder *MockCallerResourceMockRecorder
}

// MockCallerResourceMockRecorder is the mock recorder for MockCallerResource
type MockCallerResourceMockRecorder struct {
	mock *MockCallerResource
}

// NewMockCallerResource creates a new mock instance
func NewMockCallerResource(ctrl *gomock.Controller) *MockCallerResource {
	mock := &MockCallerResource{ctrl: ctrl}
	mock.recorder = &MockCallerResourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCallerResource) EXPECT() *MockCallerResourceMockRecorder {
	return m.recorder
}

// GetAttachedIamPoliciesByUserName mocks base method
func (m *MockCallerResource) GetAttachedIamPoliciesByUserName(arg0 string) (*model.Caller, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachedIamPoliciesByUserName", arg0)
	ret0, _ := ret[0].(*model.Caller)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachedIamPoliciesByUserName indicates an expected call of GetAttachedIamPoliciesByUserName
func (mr *MockCallerResourceMockRecorder) GetAttachedIamPoliciesByUserName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachedIamPoliciesByUserName", reflect.TypeOf((*MockCallerResource)(nil).GetAttachedIamPoliciesByUserName), arg0)
}

// GetIdentity mocks base method
func (m *MockCallerResource) GetIdentity() (*model.Caller, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentity")
	ret0, _ := ret[0].(*model.Caller)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdentity indicates an expected call of GetIdentity
func (mr *MockCallerResourceMockRecorder) GetIdentity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentity", reflect.TypeOf((*MockCallerResource)(nil).GetIdentity))
}
